GET http://localhost:3000/settings/general-settings
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZlcmhhdHRhaGVyMDBAZ21haWwuY29tIiwiaWF0IjoxNzQxMzkyNjE4LCJleHAiOjE3NDEzOTYyMTgsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.uvh334MuD98EtL6X2o2781BZsvC1VbPoSgqdbVSQGC0
