PATCH http://localhost:3000/settings/general-settings
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZlcmhhdHRhaGVyMDBAZ21haWwuY29tIiwiaWF0IjoxNzQxMzcwMTYwLCJleHAiOjE3NDEzNzM3NjAsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.EWSpPWyoDldWy71TO9882S9xn3gahrgHj7nvTAKExW0
Content-Type: application/json
{
"phoneNumber":"+213550123456",
"businessName":"My Business Name",
"businessDescription":"My Business Description testing 123"
}