POST http://localhost:3000/users
Content-Type:application/json
{
  "email":"ferhatmedtahar9@gmail.com",
  "firstName":"ferhat",
  "lastName":"tahar",
  "googleId": "111352299504535320089",
  "settings": {
    "city": "Algeria"
  }
}