POST http://localhost:3000/auth/refresh-tokens
Content-Type:application/json
{
  "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJpYXQiOjE3NDEzOTA0MTIsImV4cCI6MTc0MTQ3NjgxMiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIn0.BU5IBMkyoJTRzhEam6RaJSqaLKOenpZEN4ePfuNfqUU"
}