PATCH http://localhost:3000/settings/deliveries/4
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZlcmhhdHRhaGVyMDBAZ21haWwuY29tIiwiaWF0IjoxNzQxMzgyNTMyLCJleHAiOjE3NDEzODYxMzIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.HknvNDBGx465Q9M4vBpY2HbLibAafSozMwdJCR4u_qc
Content-Type:application/json
{
  "apiId":"20042004"
}