POST http://localhost:3000/products
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZlcmhhdHRhaGVyMDBAZ21haWwuY29tIiwiaWF0IjoxNzQxMzg2NjY4LCJleHAiOjE3NDEzOTAyNjgsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.ugr9ZtrYsG8_Xi_n45WhN3us8CMAqT4qy3nUfunTsRk
Content-Type:application/json
{
    "productName": "cadre",
    "description": "cadre of flowers",
    "color": "red",
    "size": "medium",
    "heavyWeight": false,
    "price": 100,
    "discount": 0.2,
    "quantity": 30,
    "imageUrl": "https://example.com/image.jpg"
}