POST http://localhost:3000/orders
Content-Type:application/json
{
  "customerName": "create from 0 d",
  "phoneNumber": "0123456789",
  "address": "Algeria, Laghouat, Laghouat",
  "status": "PENDING",
  "isExternal": false,
  "externalTrackingId": "",
  "products": [  {
      "productId": 7,
      "quantity": 20
    }
 
  ]
}