PATCH http://localhost:3000/orders/30
Content-Type:application/json
{  "customerName": "tahar ferhat",
  "phoneNumber": "0123456789",
  "address": "Laghouat",
  "status": "PENDING",
  "isExternal": false,
  "externalTrackingId": "","products":[
      {
      "productId": 7,
      "quantity": 5
    }]
}