PATCH http://localhost:3000/orders
Content-Type:application/json
{
  "customerName": "John Doe",
  "phoneNumber": "0123456789",
  "address": "123 Street, City, State",
  "status": "PENDING",
  "isExternal": false,
  "externalTrackingId": "",
}