POST http://localhost:3000/orders
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIzLCJlbWFpbCI6ImZlcmhhdHRhaGVyMDBAZ21haWwuY29tIiwiaWF0IjoxNzQxMzg2NjY4LCJleHAiOjE3NDEzOTAyNjgsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.ugr9ZtrYsG8_Xi_n45WhN3us8CMAqT4qy3nUfunTsRk
Content-Type:application/json
{
  "customerName": "create from 0 d",
  "phoneNumber": "0123456789",
  "address": "Algeria, Laghouat, Laghouat",
  "status": "PENDING",
  "isExternal": false,
  "externalTrackingId": "",
  "products": [  {
      "productId": 8,
      "quantity": 2
    }
 
  ]
}